---
  apiVersion: v1
  kind: Service
  metadata:
    name: mongo
    labels: 
      app: mongo
  spec:
    type: NodePort
    ports:
    - port: 27017
      nodePort: 32717
      protocol: TCP
    selector:
      app: mongo
  ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mongo-deploy
      labels:
        app: mongo
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: mongo
      minReadySeconds: 5
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: mongo
        spec:
          containers:
            - name: mongo-pod
              image: mongo:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 27017