name: sample_beacons
description: This is the sample Data microservice.
homepage: https://github.com/pip-services-samples/pip-services-beacons-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies: 
  pip_services3_commons: ^1.1.4
